defaults:
  - override job_logging: colorlog
  - override hydra_logging: colorlog

run:
  dir: "outputs/${mode}/${experiment_name}-${now:%Y-%m-%d_%H-%M-%S}"
sweep:
  dir: "outputs/sweeps/${mode}/${experiment_name}-${now:%Y-%m-%d_%H-%M-%S}"
  subdir: ${hydra.job.override_dirname}
job:
  config:
    override_dirname:
      exclude_keys:
        - experiment
        - params_search
job_logging:
  handlers:
    file:
      filename: ${hydra.runtime.output_dir}/${mode}.log
