_target_: src.model.example_classification_model.lightning_module.ClassificationLitModule

net:
  _target_: src.model.example_classification_model.torch_model.ExampleClassificationCNN
  num_classes: 10
  dropout_rate: 0.1
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
loss_fn:
  _target_: torch.nn.functional.cross_entropy
  _partial_: true
scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 5
  gamma: 0.1
  _partial_: true
