defaults:
  - _self_
  - model: ???
  - data: ???
  - trainer: default
  - experiment: ???
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

ckpt_path: ??? # User must override this
data_split: "test" # one of: test or val

hydra:
  run:
    dir: "outputs/eval/${experiment_name}-${now:%Y-%m-%d_%H-%M-%S}"
