defaults:
  - model: example_model
  - data: example_data
  - trainer: default

experiment_name: "eval"
ckpt_path: ??? # User must override this
eval_split: "test" # one of: test or val

hydra:
  run:
    dir: "eval_output/${experiment_name}-${now:%Y-%m-%d_%H-%M-%S}"
