defaults:
  - model: ???
  - data: ???
  - trainer: default
  - experiment: ???

ckpt_path: ??? # User must override this
data_split: "test" # one of: train, test, val, or predict
save_format: csv # json or csv

hydra:
  run:
    dir: "outputs/predict/${experiment_name}-${now:%Y-%m-%d_%H-%M-%S}"
