defaults:
  - _self_
  - model: ???
  - data: ???
  - trainer: default
  - experiment: ???
  - hydra: default

mode: predict
ckpt_path: ??? # User must override this
data_split: "test" # one of: train, test, val, or predict
save_format: csv # json or csv
