defaults:
  - _self_
  - model: example_model
  - data: example_data
  - trainer: default
  - experiment: null # Optional, can override experiment

hydra:
  run:
    dir: "outputs/train/${experiment_name}-${now:%Y-%m-%d_%H-%M-%S}"
