defaults:
  - _self_
  - model: example_model
  - data: example_data
  - trainer: default

seed: 42
skip_test: False
experiment_name: "exp"

hydra:
  run:
    dir: "train_output/${experiment_name}-${now:%Y-%m-%d_%H-%M-%S}"
