# @package _global_

defaults:
  - override /hydra/sweeper: optuna

# Make sure this is aligned with the metric logged in lightning module
optimized_metric: "val_multiclassaccuracy"

# See: https://hydra.cc/docs/plugins/optuna_sweeper/
hydra:
  mode: "MULTIRUN"
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: null
    n_jobs: 1
    direction: maximize
    n_trials: 3

    #You can choose TPEsampler, RandomSampler, GridSampler, etc.
    # See: https://optuna.readthedocs.io/en/stable/reference/samplers/index.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
      n_startup_trials: 3 # number of random sampling runs before optimization starts

    # Hyperparameter search space
    params:
      model.optimizer.lr: interval(0.0001, 0.1)
      data.batch_size: choice(32, 64)
