name: CI Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci_checks:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.11", "3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -


      - name: Check PAT_TOKEN secret
        run: |
          if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
            echo "PAT_TOKEN is not set!"
            exit 1
          else
            echo "PAT_TOKEN is set"
          fi
      - name: Ensure lock file is up-to-date
        run: |
          # Regenerate the lock file
          poetry lock
      
          # Configure git for GitHub Actions
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
          # Add changes if there are any
          git add poetry.lock
      
          # Commit changes (ignore if nothing to commit)
          git commit -m "Update poetry.lock from CI" || echo "No changes to commit"
      
          # Push to the branch (create it if it doesn't exist)
          git push --set-upstream https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git HEAD:auto-update-lock-file  

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-ansi

      - name: Run Pre-commit
        run: |
          python3 -m pip install --upgrade pip
          pip install pre-commit
          pre-commit run --all-files

      - name: Run tests
        run: |
          poetry run pytest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
